name: objectbox_inspector
description: "A visual interface for all the classes annotated with @Entity in ObjectBox."
version: 2.1.1
homepage: https://github.com/ccosnean/objectbox-inspector/tree/main/objectbox_inspector

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^5.1.0
  path: ^1.9.1
  date_field: ^6.0.0

dev_dependencies:
  flutter_lints: ">=3.0.0 <4.0.0"
