name: objectbox_inspector_generator
description: "The generator for objectbox_inspector, getInspectableBoxes mainly, that is required by openObjectboxInspector."
version: 2.1.0
homepage: https://github.com/ccosnean/objectbox-inspector/tree/main/objectbox_inspector_generator

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  build: ">=3.0.0 <=4.0.3"
  analyzer: '>=7.0.0 <=9.0.0'
  objectbox: ^5.1.0
  source_gen: ">=3.0.0 <=4.1.1"
  dart_style: ">=2.0.0 <=3.1.3"
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_lints: ">=3.0.0 <4.0.0"
